Entregable-origamiMobile/config/routes.rb
Rails.application.routes.draw do
  resources :origamis
  resources :favorigamis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'origamis#acerca'
  get 'acerca' => 'origamis#acerca'
  get 'origamis/:id/favourite' => 'origamis#favourite_management', as: :origamis_favourite
end

Entregable-origamiMobile/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Entregable-origamiMobile/app/models/origami.rb
class Origami < ApplicationRecord
mount_uploader :imagen, ImageUploader
default_scope {order 'lower(name)'}
scope :favs, ->{where("origamis.favourite = ?", true)}
end

Entregable-origamiMobile/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Entregable-origamiMobile/app/controllers/favorigamis_controller.rb
class FavorigamisController < ApplicationController
def index
  @origamis = Origami.favs
end
end

Entregable-origamiMobile/app/controllers/origamis_controller.rb
class OrigamisController < ApplicationController
  before_action :set_origami, only: [:show, :edit, :update, :destroy, :favourite_management]

  # GET /origamis
  # GET /origamis.json
  def index
      if(params[:favoritos])
        @origamis = Origami.favs
      else
        @origamis = Origami.all
      end
  end

  # GET /origamis/1
  # GET /origamis/1.json
  def show
  end

  # GET /origamis/new
  def new
    @origami = Origami.new
  end

  # GET /origamis/1/edit
  def edit
  end

  # POST /origamis
  # POST /origamis.json
  def create
    @origami = Origami.new(origami_params)

    respond_to do |format|
      if @origami.save
        format.html { redirect_to @origami, notice: 'Origami was successfully created.' }
        format.json { render :show, status: :created, location: @origami }
      else
        format.html { render :new }
        format.json { render json: @origami.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origamis/1
  # PATCH/PUT /origamis/1.json
  def update
    respond_to do |format|
      if @origami.update(origami_params)
        format.html { redirect_to @origami, notice: 'Origami was successfully updated.' }
        format.json { render :show, status: :ok, location: @origami }
      else
        format.html { render :edit }
        format.json { render json: @origami.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origamis/1
  # DELETE /origamis/1.json
  def destroy
    @origami.destroy
    respond_to do |format|
      format.html { redirect_to origamis_url, notice: 'Origami was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favourite_management
    if(@origami.favourite)
      @origami.favourite = false
    else 
      @origami.favourite = true
    end
    @origami.save
    redirect_back fallback_location: origamis_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origami
      @origami = Origami.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def origami_params
      params.require(:origami).permit(:name, :dificultad, :categoria, :imagen, :favourite)
    end
    
    
end

Entregable-origamiMobile/app/helpers/application_helper.rb
module ApplicationHelper
end

Entregable-origamiMobile/app/helpers/fav_origamis_helper.rb
module FavOrigamisHelper
end

Entregable-origamiMobile/app/helpers/favorigamis_helper.rb
module FavorigamisHelper
end

Entregable-origamiMobile/app/helpers/origames_helper.rb
module OrigamesHelper
end

Entregable-origamiMobile/app/helpers/origamis_helper.rb
module OrigamisHelper
end

Entregable-origamiMobile/app/views/favorigamis/index.html.erb
<p id="notice"><%= notice %></p>

<%= content_for :titulo, "Origamis"%>
<%= content_for :botones do %>
  <%= link_to "Nuevo", new_origami_path, class: "ui-btn ui-btn-right ui-corner-all ui-btn-icon-right ui-icon-plus ui-mini"%>
<% end %>
            <form class="ui-filterable">
                <input id="filter-input" data-type="search">
            </form>

            <ul data-role="listview"
                data-autodividers="true"
                data-filter="true"
                data-input="#filter-input"
            >
              <% @origamis.each do |origami|%>
                <li class="ui-li-has-thumb">
                  <%= link_to origami, data:{ajax:"false"} do%>
                     <%= image_tag(origami.imagen_url(:thumb)) if origami.imagen.present?%>
                     <h3><%= origami.name%></h3>
                  <%end%>
                </li>
              <%end%>
                </ul>

Entregable-origamiMobile/app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>OrigamiMobile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
  
  <div data-role="page" data-theme="b">

        <div data-role="header">
            <h1><%= yield :titulo %></h1>
            <%= yield :botones %>
        </div>

        <div class="ui-content" role="main">
                <%= yield %>
        </div>

        <div data-role="footer" data-position="fixed">
            <div data-role="navbar">

    <ul >

          <li> <%= link_to 'Nosotros', root_path,class: "ui-btn ui-btn-icon-top ui-icon-info #{ @origamis.present? ? '' : 'ui-btn-active'} ", data: {ajax: "false"} %></li>

          <li><%= link_to 'Origamis', origamis_path,  class: "ui-btn ui-btn-icon-top ui-icon-bars  #{ @origamis.present? && params[:favoritos].nil? ? 'ui-btn-active' : ''} " , data: {ajax: "false"} %></li>
          
          <li><%= link_to 'Origamis', origamis_path(favoritos: true),  class: "ui-btn ui-btn-icon-top ui-icon-star  #{ params[:favoritos].present? ? 'ui-btn-active' : ''} " , data: {ajax: "false"} %></li>></li>

    </ul>
            </div>
        </div>

    </div>
    <div data-role="page" data-theme="b" id="about">

        <div data-role="header" data-add-back-btn="true">
            <h1>Chips & Ketchup</h1>
        </div>

        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquid amet at blanditiis consequatur
            cupiditate deserunt dicta ea enim error et explicabo fuga hic illum impedit, iste itaque iure neque odio
            optio, perspiciatis quam quasi qui ratione similique tempore veritatis?
        </div>

        <div data-role="footer" data-position="fixed">
            <div data-role="navbar">
                <ul >
                    <li><a href="#about" data-transition="slide" class="ui-btn ui-btn-icon-top ui-icon-info">About us!</a></li>
                    <li><a href="chips.html" class="ui-btn ui-btn-icon-top ui-icon-bars"
                     data-ajax="false">Chips!</a></li>
                    <li><a href="chips.html?favs=true" class="ui-btn ui-btn-icon-top ui-icon-star"
                    data-ajax="false">Favourite chips!</a></li>
                </ul>
            </div>
        </div>

    </div>
  </body>
</html>

Entregable-origamiMobile/app/views/origamis/_form.html.erb
<%= form_with(model: origami, local: true, html: {multipart: true, 'data-ajax' => false}) do |form| %>
  <% if origami.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(origami.errors.count, "error") %> prohibited this origami from being saved:</h2>

      <ul>
      <% origami.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :origami_name %>
  </div>

  <div class="field">
    <%= form.label :dificultad %>
    <%= form.text_field :dificultad, id: :origami_dificultad %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria, id: :origami_categoria %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.file_field :imagen, id: :origami_imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Entregable-origamiMobile/app/views/origamis/acerca.html.erb
<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid architecto debitis ea enim
                incidunt laborum quasi quia reprehenderit sapiente. Asperiores, atque deserunt dignissimos, distinctio
                dolore eum expedita facere facilis fuga hic, iusto labore libero quam quia recusandae reiciendis
                voluptatem.
            </div>
            
            <h1>NUEVO ORIGAMI Y OTRO MÁS</h1>
            
<%= content_for :titulo, "OrigamiMania"%>

Entregable-origamiMobile/app/views/origamis/edit.html.erb
<h1>Editing Origami</h1>

<%= render 'form', origami: @origami %>

<%= link_to 'Show', @origami %> |
<%= link_to 'Back', origamis_path %>

Entregable-origamiMobile/app/views/origamis/index.html.erb
<p id="notice"><%= notice %></p>

<%= content_for :titulo, "Origamis"%>
<%= content_for :botones do %>
  <%= link_to "Nuevo", new_origami_path, class: "ui-btn ui-btn-right ui-corner-all ui-btn-icon-right ui-icon-plus ui-mini"%>
<% end %>
            <form class="ui-filterable">
                <input id="filter-input" data-type="search">
            </form>

            <ul data-role="listview"
                data-autodividers="true"
                data-filter="true"
                data-input="#filter-input"
            >
              <% @origamis.each do |origami|%>
                <li class="ui-li-has-thumb">
                  <%= link_to origami, data:{ajax:"false"} do%>
                     <%= image_tag(origami.imagen_url(:thumb)) if origami.imagen.present?%>
                     <h3><%= origami.name%></h3>
                  <%end%>
                </li>
              <%end%>
                </ul>

Entregable-origamiMobile/app/views/origamis/new.html.erb
<h1>New Origami</h1>

<%= render 'form', origami: @origami %>

<%= link_to 'Back', origamis_path %>

Entregable-origamiMobile/app/views/origamis/show.html.erb
<p id="notice"><%= notice %></p>
<%= content_for :botones do %>
  <%= link_to "Back", origamis_path, {"data-rel"=>"back", class: "ui-btn ui-btn-left ui-corner-all ui-btn-icon-left ui-icon-back ui-mini"}%>
<% end %>
<%= content_for :titulo, @origami.name%>
<p>
  <strong>Dificultad:</strong>
  <%= @origami.dificultad %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @origami.categoria %>
</p>

<p>
  <%= image_tag(@origami.imagen_url, id:"img-origami") if @origami.imagen.present? %>
</p>
<div class="ui-grid-b ui-mini " id="showbotones">
		  <div class= "ui-block-a">
		    <%if @origami.favourite%>
		      <%= link_to "Quitar de favoritos", origamis_favourite_path, {class: "ui-btn ui-icon-delete ui-btn-icon-top ui-btn-b ui-corner-all"} %>
		    <% else %>
		      <%= link_to "Añadir a favoritos", origamis_favourite_path, {class: "ui-btn ui-icon-plus ui-btn-icon-top ui-btn-b ui-corner-all"} %>
		    <% end %>
		  </div>

		  <div class= "ui-block-b">
				<%= link_to "Editar", edit_origami_path(@origami), {class: "ui-btn ui-icon-info ui-btn-icon-top ui-btn-b ui-corner-all"} %>
		  </div>

		  <div class= "ui-block-c">
				<%= link_to "Eliminar", @origami_path, {data: {confirm: "¿estás seguro?"}, method: "delete", class: "ui-btn ui-icon-delete ui-btn-icon-top ui-btn-a ui-corner-all"} %>
		  </div>
	</div>
<%= link_to 'Edit', edit_origami_path(@origami) %> |
<%= link_to 'Back', origamis_path %>